// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaCX7jVDJvSM5FEA_miWDHplioR01gKOA',
    appId: '1:324522060493:web:50e59ce8be224645541784',
    messagingSenderId: '324522060493',
    projectId: 'chat-app-440a7',
    authDomain: 'chat-app-440a7.firebaseapp.com',
    storageBucket: 'chat-app-440a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMujulRh2k7B-86zZILGbRKgBGQTNDKGU',
    appId: '1:324522060493:android:47bfad3fde07e0c8541784',
    messagingSenderId: '324522060493',
    projectId: 'chat-app-440a7',
    storageBucket: 'chat-app-440a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Pc0SJIq2GgN7JenVDYe2V-7pt0MFepE',
    appId: '1:324522060493:ios:3a55270c43e0fd62541784',
    messagingSenderId: '324522060493',
    projectId: 'chat-app-440a7',
    storageBucket: 'chat-app-440a7.firebasestorage.app',
    iosBundleId: 'com.example.masteryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Pc0SJIq2GgN7JenVDYe2V-7pt0MFepE',
    appId: '1:324522060493:ios:3a55270c43e0fd62541784',
    messagingSenderId: '324522060493',
    projectId: 'chat-app-440a7',
    storageBucket: 'chat-app-440a7.firebasestorage.app',
    iosBundleId: 'com.example.masteryFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaCX7jVDJvSM5FEA_miWDHplioR01gKOA',
    appId: '1:324522060493:web:cbeb0c9568e1214d541784',
    messagingSenderId: '324522060493',
    projectId: 'chat-app-440a7',
    authDomain: 'chat-app-440a7.firebaseapp.com',
    storageBucket: 'chat-app-440a7.firebasestorage.app',
  );
}
